BEGIN;

insert into blogful_articles (title, date_published, content) values ('Fingersmith', '10/1/2019', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into blogful_articles (title, date_published, content) values ('Now and Forever', '8/7/2019', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.');
insert into blogful_articles (title, date_published, content) values ('Very Potter Musical, A', '10/11/2019', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into blogful_articles (title, date_published, content) values ('Just the Ticket', '9/16/2019', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into blogful_articles (title, date_published, content) values ('Once Upon a Time in China II (Wong Fei-hung Ji Yi: Naam yi dong ji keung)', '1/26/2019', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into blogful_articles (title, date_published, content) values ('Perfect Candidate, A', '5/3/2019', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into blogful_articles (title, date_published, content) values ('Total Recall', '9/15/2019', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into blogful_articles (title, date_published, content) values ('Madame Tutli-Putli', '4/1/2019', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into blogful_articles (title, date_published, content) values ('21 Grams', '7/21/2019', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into blogful_articles (title, date_published, content) values ('Who Is Killing the Great Chefs of Europe?', '1/26/2019', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into blogful_articles (title, date_published, content) values ('Sin Retorno', '1/31/2019', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into blogful_articles (title, date_published, content) values ('Love Serenade', '1/2/2019', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into blogful_articles (title, date_published, content) values ('Public Eye, The', '9/8/2019', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.');
insert into blogful_articles (title, date_published, content) values ('Shaolin Temple (Shao Lin si)', '12/30/2018', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
insert into blogful_articles (title, date_published, content) values ('Palmetto', '2/25/2019', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.');
insert into blogful_articles (title, date_published, content) values ('Ravenous', '12/12/2018', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.');
insert into blogful_articles (title, date_published, content) values ('Raising Cain', '8/7/2019', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into blogful_articles (title, date_published, content) values ('Choke', '10/22/2019', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into blogful_articles (title, date_published, content) values ('2 Fast 2 Furious (Fast and the Furious 2, The)', '2/11/2019', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.');
insert into blogful_articles (title, date_published, content) values ('Always for Pleasure', '11/7/2018', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into blogful_articles (title, date_published, content) values ('On the Road to Emmaus (Emmauksen tiellä)', '2/6/2019', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into blogful_articles (title, date_published, content) values ('Glass Menagerie, The', '1/6/2019', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');

COMMIT;

/* INSERT INTO blogful_articles
    (title, date_published, content)
VALUES
  ('article1', '2016-01-16 12:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
  ('article2', '2016-05-01 15:00:00', 'Shape of Pooh'),
  ('article3', '2017-02-22 12:00:00', 'UpTown Monk'),
  ('article4', '2017-04-04 08:00:00', 'Despotato'),
  ('article5', '2017-04-23 15:00:00', 'Despotato'),
  ('article6', '2017-08-11 13:00:00', 'Cats that teach SQL'),
  ('article7', '2017-12-09 17:00:00', 'Despotato'),
  ('article8', '2018-01-24 19:00:00', 'Cats that teach SQL'),
  ('article9', '2018-01-29 11:00:00',  'Man''s not torrid'),
  ('article10', '2018-02-13 05:00:00', 'UpTown Monk'),
  ('article11', '2018-03-13 09:00:00', 'Shape of Pooh'),
  ('article12', '2018-03-31 13:00:00', 'UpTown Monk'),
  ('article13', '2019-04-03 07:00:00', 'Despotato'),
  ('article14', '2019-05-05 21:00:00', 'UpTown Monk'),
  ('article15', '2018-02-17 05:00:00', 'Man''s not torrid'),
  ('article16', '2018-04-17 05:00:00', 'Despotato'),
  ('article17', '2018-02-13 05:00:00', 'Cats that teach SQL'),
  ('article18', '2018-02-13 05:00:00', 'UpTown Monk'),
  ('article19', '2018-02-13 05:00:00', 'Despotato'),
  ('article20', '2018-02-13 05:00:00', 'Shape of Pooh'),
  ('article21', '2018-02-13 05:00:00', 'Shape of Pooh');
 */
